Models/Doors.cs
using Doors2Heaven.Data;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Doors2Heaven.Models
{
    public class DoorsContext : ApplicationDbContext
    {
        public DoorsContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }
        public DbSet<Doors> Doors { get; set; }
    }
    public class Doors
    {
        public int Id { get; set; }
        public string? Types_of_Door { get; set; }
        public string? Style_of_Door { get; set; }
        public string? Features { get; set; }
        public decimal Price { get; set; }
        public string? Material { get; set; }
        public string? Ratings { get; set; }
    }
}

Controllers/DoorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Doors2Heaven.Data;
using Doors2Heaven.Models;
using Microsoft.AspNetCore.Authorization;

namespace Doors2Heaven.Controllers
{
    public class DoorsController : Controller
    {
        private readonly Doors2HeavenContext _context;

        public DoorsController(Doors2HeavenContext context)
        {
            _context = context;
        }

        // GET: Doors
        /*public async Task<IActionResult> Index()
        {
            return View(await _context.Doors.ToListAsync());
        }*/
        [Authorize]
        public async Task<IActionResult> Index(string movieGenre, string searchString)
        {
            if (_context.Doors == null)
            {
                return Problem("Entity set 'DoorsContext.Doors'  is null.");
            }

            // Use LINQ to get list of genres.
            IQueryable<string> genreQuery = from m in _context.Doors
                                            orderby m.Material
                                            select m.Material;
            var movies = from m in _context.Doors
                         select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Types_of_Door!.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(movieGenre))
            {
                movies = movies.Where(x => x.Material == movieGenre);
            }

            var movieGenreVM = new DoorMaterialViewModel
            {
                Material = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Doors = await movies.ToListAsync()
            };

            return View(movieGenreVM);
        }

        // GET: Doors/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doors = await _context.Doors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doors == null)
            {
                return NotFound();
            }

            return View(doors);
        }

        // GET: Doors/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Doors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Types_of_Door,Style_of_Door,Features,Price,Material,Ratings")] Doors doors)
        {
            if (ModelState.IsValid)
            {
                _context.Add(doors);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(doors);
        }

        // GET: Doors/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doors = await _context.Doors.FindAsync(id);
            if (doors == null)
            {
                return NotFound();
            }
            return View(doors);
        }

        // POST: Doors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Types_of_Door,Style_of_Door,Features,Price,Material,Ratings")] Doors doors)
        {
            if (id != doors.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(doors);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DoorsExists(doors.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(doors);
        }

        // GET: Doors/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var doors = await _context.Doors
                .FirstOrDefaultAsync(m => m.Id == id);
            if (doors == null)
            {
                return NotFound();
            }

            return View(doors);
        }

        // POST: Doors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var doors = await _context.Doors.FindAsync(id);
            if (doors != null)
            {
                _context.Doors.Remove(doors);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DoorsExists(int id)
        {
            return _context.Doors.Any(e => e.Id == id);
        }
    }
}

Views/Doors/Create.cshtml
@model Doors2Heaven.Models.Doors

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Doors</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Types_of_Door" class="control-label"></label>
                <input asp-for="Types_of_Door" class="form-control" />
                <span asp-validation-for="Types_of_Door" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Style_of_Door" class="control-label"></label>
                <input asp-for="Style_of_Door" class="form-control" />
                <span asp-validation-for="Style_of_Door" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Features" class="control-label"></label>
                <input asp-for="Features" class="form-control" />
                <span asp-validation-for="Features" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Material" class="control-label"></label>
                <input asp-for="Material" class="form-control" />
                <span asp-validation-for="Material" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ratings" class="control-label"></label>
                <input asp-for="Ratings" class="form-control" />
                <span asp-validation-for="Ratings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Doors/Delete.cshtml
@model Doors2Heaven.Models.Doors

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doors</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Types_of_Door)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Types_of_Door)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Style_of_Door)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Style_of_Door)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Features)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Features)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Material)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Material)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ratings)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ratings)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Doors/Details.cshtml
@model Doors2Heaven.Models.Doors

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Doors</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Types_of_Door)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Types_of_Door)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Style_of_Door)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Style_of_Door)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Features)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Features)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Material)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Material)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ratings)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ratings)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Doors/Edit.cshtml
@model Doors2Heaven.Models.Doors

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Doors</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Types_of_Door" class="control-label"></label>
                <input asp-for="Types_of_Door" class="form-control" />
                <span asp-validation-for="Types_of_Door" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Style_of_Door" class="control-label"></label>
                <input asp-for="Style_of_Door" class="form-control" />
                <span asp-validation-for="Style_of_Door" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Features" class="control-label"></label>
                <input asp-for="Features" class="form-control" />
                <span asp-validation-for="Features" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Material" class="control-label"></label>
                <input asp-for="Material" class="form-control" />
                <span asp-validation-for="Material" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ratings" class="control-label"></label>
                <input asp-for="Ratings" class="form-control" />
                <span asp-validation-for="Ratings" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Doors/Index.cshtml
<style>
    th, td {
        color: black;
        font-weight: bolder;
    }
</style>
@model Doors2Heaven.Models.DoorMaterialViewModel
@{
    ViewData["Title"] = "Index";
}

<h1 style="color: black; font-weight: bolder;">Index</h1>

@if(User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<form asp-controller="Doors" asp-action="Index" method="get">
    <p>
        <select asp-for="DoorMaterial" asp-items="Model.Material">
            <option value="">All</option>
        </select>

        Title: <input type="text" asp-for="SearchString" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Doors![0].Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doors![0].Types_of_Door)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doors![0].Style_of_Door)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doors![0].Features)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doors![0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doors![0].Material)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Doors![0].Ratings)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Doors!) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Types_of_Door)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Style_of_Door)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Features)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Material)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ratings)
            </td>
            @if(User.IsInRole("Admin"))
            {
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            }
        </tr>
}
    </tbody>
</table>